events {}

http {
    upstream react_app {
        server <worker1_ip>:<nodeport_react>; # Replace with actual worker1 IP and NodePort for React
        server <worker2_ip>:<nodeport_react>; # Replace with actual worker2 IP and NodePort for React
    }

    upstream flask_api {
        server <worker1_ip>:<nodeport_flask>; # Replace with actual worker1 IP and NodePort for Flask
        server <worker2_ip>:<nodeport_flask>; # Replace with actual worker2 IP and NodePort for Flask
    }

    server {
        listen 80;
        server_name food-fe.poridhi.io;

        location / {
            proxy_pass http://react_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name food-api.poridhi.io;

        location / {
            proxy_pass http://flask_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

